import { Scale, AlertTriangle, Info } from "lucide-react";
import { Layout } from "@/components/layout/Layout";

export default function Disclaimer() {
  return (
    <Layout>
      <div className="container py-16 max-w-3xl">
        <h1 className="text-3xl font-bold mb-8">Legal Disclaimer</h1>
        
        <div className="prose prose-invert max-w-none space-y-6">
          <section className="audit-card border-warning/30">
            <div className="flex items-start gap-3">
              <AlertTriangle className="h-6 w-6 text-warning flex-shrink-0 mt-1" />
              <div>
                <h2 className="text-xl font-semibold mb-4">Important Notice</h2>
                <p className="text-muted-foreground leading-relaxed">
                  This platform is for informational and consumer awareness purposes only. 
                  The information presented should not be construed as legal advice, accusation 
                  of wrongdoing, or definitive proof of deceptive practices.
                </p>
              </div>
            </div>
          </section>

          <section className="audit-card">
            <h2 className="text-xl font-semibold mb-4 flex items-center gap-2">
              <Scale className="h-5 w-5 text-primary" />
              Purpose of Platform
            </h2>
            <p className="text-muted-foreground leading-relaxed">
              UnMask serves as a consumer awareness and social audit platform. Our purpose is to:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-2">
              <li>Aggregate publicly available advertising data</li>
              <li>Identify potential conflicts in topper claims</li>
              <li>Provide tools for consumers to make informed decisions</li>
              <li>Facilitate the exercise of consumer protection rights</li>
            </ul>
          </section>

          <section className="audit-card">
            <h2 className="text-xl font-semibold mb-4 flex items-center gap-2">
              <Info className="h-5 w-5 text-muted-foreground" />
              Data Accuracy
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              The data on this platform comes from user submissions and AI-powered extraction. 
              While we strive for accuracy, we cannot guarantee:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2">
              <li>Accuracy of AI-extracted information from images</li>
              <li>Correctness of user-provided manual entries</li>
              <li>Completeness of conflict detection</li>
              <li>Validity of calculated deception scores</li>
            </ul>
            <p className="text-muted-foreground mt-4">
              Users should independently verify information before taking any action.
            </p>
          </section>

          <section className="audit-card">
            <h2 className="text-xl font-semibold mb-4">Not Legal Advice</h2>
            <p className="text-muted-foreground leading-relaxed">
              The CCPA report templates and complaint documents generated by this platform are 
              templates only. They do not constitute legal advice and should be reviewed by 
              qualified legal professionals before submission to any authority. UnMask is not 
              a law firm and does not provide legal services.
            </p>
          </section>

          <section className="audit-card">
            <h2 className="text-xl font-semibold mb-4">No Accusations</h2>
            <p className="text-muted-foreground leading-relaxed">
              A "conflict" or high "deception score" does not automatically mean an institute 
              has engaged in deceptive practices. There may be legitimate reasons for 
              overlapping claims, such as:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-2">
              <li>Students genuinely attending multiple institutes</li>
              <li>Different programs or time periods</li>
              <li>Legitimate coaching arrangements</li>
              <li>Data entry errors or misidentification</li>
            </ul>
          </section>

          <section className="audit-card">
            <h2 className="text-xl font-semibold mb-4">Fair Use of Public Records</h2>
            <p className="text-muted-foreground leading-relaxed">
              This platform uses publicly available newspaper advertisements for consumer 
              awareness purposes. This constitutes fair use under copyright law for purposes 
              of criticism, comment, news reporting, and scholarship. Original advertisements 
              remain the property of their respective publishers and advertisers.
            </p>
          </section>

          <section className="audit-card">
            <h2 className="text-xl font-semibold mb-4">Indemnification</h2>
            <p className="text-muted-foreground leading-relaxed">
              By using this platform, you agree to indemnify and hold harmless UnMask and its 
              operators from any claims, damages, or expenses arising from your use of the 
              platform, your submissions, or your reliance on platform data.
            </p>
          </section>

          <section className="audit-card">
            <h2 className="text-xl font-semibold mb-4">Jurisdiction</h2>
            <p className="text-muted-foreground leading-relaxed">
              This platform operates under the laws of India. Any disputes shall be subject 
              to the exclusive jurisdiction of courts in India. International users should 
              be aware of and comply with their local laws regarding consumer protection 
              platforms.
            </p>
          </section>
        </div>
      </div>
    </Layout>
  );
}
